spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mammadzadacavid0@gmail.com
    password: uestdcniovgoajog
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
