spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.javid.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.javid.notification.kafka.payment.PaymentConfirmation
server:
  port: 8140